# Generated by Django 5.0 on 2024-01-11 13:07

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0001_initial"),
        ("rating", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="rating",
            unique_together={("owner", "product")},
        ),
    ]
